.\" Gelide manpage.
.\" Copyright © 2008 - 2010 Juan Ángel Moreno Fernández
.\"
.TH Gelide "19" "October 2008" "" ""
.SH NAME
Gelide \- A multi system and multi emulator frontend for GNU/Linux

.SH SYNOPSIS
.B gelide

.SH DESCRIPTION
.B Gelide
is a configurable frontend used to manage any kind of emulated system 
(Video game console, Arcade, Pc) also let you catalog and launch any game's
emulator under Gnu/Linux.

It support a wide range of systems and a wide range of emulators driven by
console parameters and have some of them preconfigured.

Gelide is a free project licensed under the GNU General Public License and is
written in C++ using Gtkmm libraries.

.SH BUGS
Please report any bugs to the Gelide bug tracker at Sourceforge.net
.TP
\fIhttp://sourceforge.net/projects/gelide\fP
.TP
or directly to
.TP
\fIgelide.prj@gmail.com\fP.

.SH CONTACT
Juan Ángel Moreno Fernández <\fIjamf@users.sourceforge.net\fP>
.TP
\fIhttp://gelide.sourceforge.net\fP

.SH AUTHOR
Written by Juan Ángel Moreno Fernández <gelide.prj@gmail.com>
